"use client";

import { motion } from "framer-motion";
import { MapPin, BookOpen, Mail, BarChart2, Scale, Users } from "lucide-react";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const STEPS = [
  {
    n: "01", Icon: MapPin,
    title: "Enter your ZIP",
    desc: "We identify your House representative and two U.S. Senators — the three people who vote on federal laws on your behalf. Coverage for all 50 states.",
  },
  {
    n: "02", Icon: BookOpen,
    title: "Explore live bills",
    desc: "Browse legislation fetched directly from Congress.gov. Filter by policy area, legislative stage, or chamber. AI-powered plain-English summaries for every bill.",
  },
  {
    n: "03", Icon: BarChart2,
    title: "Understand the stakes",
    desc: "See how likely each bill is to pass. Read balanced pros and cons. Understand what each bill means for your community and congressional district.",
  },
  {
    n: "04", Icon: Scale,
    title: "See both sides",
    desc: "Every bill's perspectives panel shows arguments for and against — generated by AI, verified nonpartisan. Who supports it? Who opposes it and why?",
  },
  {
    n: "05", Icon: Mail,
    title: "Contact your reps",
    desc: "Generate a personalized letter or phone call script for any representative. One click copies it; another opens their official contact page.",
  },
  {
    n: "06", Icon: Users,
    title: "Share with friends",
    desc: "Share a plain-English summary of any bill with one tap. Help your community stay informed and engaged in the democratic process.",
  },
];

export default function HowItWorksPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#f4f2ee", display: "flex", flexDirection: "column" }}>
      <Navbar />

      {/* Header */}
      <div style={{ background: "#0d1f3c", padding: "48px 28px 56px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", textAlign: "center" }}>
          <h1 style={{ fontFamily: "var(--font-playfair)", fontSize: 40, fontWeight: 700,
            color: "white", marginBottom: 14 }}>
            How CivicSpark Works
          </h1>
          <p style={{ fontSize: 16, color: "#8da4c4", maxWidth: 520, margin: "0 auto",
            lineHeight: 1.7, fontFamily: "var(--font-dm-sans)" }}>
            From ZIP code to constituent letter in under a minute.
            No account required. Always free. Always nonpartisan.
          </p>
        </div>
      </div>

      {/* Steps */}
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "56px 28px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 24 }}>
          {STEPS.map(({ n, Icon, title, desc }, i) => (
            <motion.div key={n}
              initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07, duration: 0.45, ease: "easeOut" }}
              style={{ background: "white", borderRadius: 16, padding: "28px 26px",
                border: "1.5px solid #e6e2d8", boxShadow: "0 2px 8px rgba(13,31,60,0.05)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 16 }}>
                <div style={{ width: 44, height: 44, borderRadius: 12, flexShrink: 0,
                  background: "linear-gradient(135deg, #0d1f3c, #1e4080)",
                  display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <Icon size={20} color="white" strokeWidth={1.8} />
                </div>
                <span style={{ fontFamily: "var(--font-playfair)", fontSize: 32, fontWeight: 700,
                  color: "#e6e2d8" }}>{n}</span>
              </div>
              <h3 style={{ fontFamily: "var(--font-playfair)", fontSize: 19, fontWeight: 700,
                color: "#0d1f3c", marginBottom: 10 }}>{title}</h3>
              <p style={{ fontSize: 13.5, color: "#7a8699", lineHeight: 1.7,
                fontFamily: "var(--font-dm-sans)", margin: 0 }}>{desc}</p>
            </motion.div>
          ))}
        </div>

        {/* CTA */}
        <div style={{ textAlign: "center", marginTop: 56, padding: "48px 28px",
          background: "#0d1f3c", borderRadius: 20 }}>
          <h2 style={{ fontFamily: "var(--font-playfair)", fontSize: 28, fontWeight: 700,
            color: "white", marginBottom: 14 }}>
            Ready to get started?
          </h2>
          <p style={{ fontSize: 14, color: "#8da4c4", marginBottom: 28,
            fontFamily: "var(--font-dm-sans)" }}>
            Find your representatives and explore legislation in under 30 seconds.
          </p>
          <Link href="/bills" style={{ display: "inline-flex", alignItems: "center", gap: 8,
            padding: "13px 28px", borderRadius: 10, fontSize: 14, fontWeight: 700,
            textDecoration: "none", background: "#b8830e", color: "white",
            fontFamily: "var(--font-dm-sans)", boxShadow: "0 4px 18px rgba(184,131,14,0.35)" }}>
            Browse Bills →
          </Link>
        </div>
      </div>
    </div>
  );
}
