import type { CivicMission, MissionResponse } from "./types";

export const DEMO_MISSION: CivicMission = {
  id: "mission-kosm-s278",
  code: "SPARK6",
  title: "Should social media work differently for teens?",
  kicker: "A live Senate bill · Digital life",
  description: "Investigate a proposal that would change who can use social media and how platforms recommend content to young people.",
  scenario: "Your feed decides what you see next—often before you have time to choose. Congress is considering rules that could change social media for people your age. The tradeoff is not simply safety versus freedom: it is about who should make those choices, what platforms must change, and what evidence should guide the law.",
  gradeBand: "9–10",
  learningObjective: "Use primary sources to distinguish what a bill says from arguments people make about it, then communicate a supported position.",
  estimatedMinutes: 10,
  status: "published",
  bill: {
    congress: 119,
    type: "S.",
    number: "278",
    title: "Kids Off Social Media Act",
    latestAction: "Introduced in the Senate and referred to the Committee on Commerce, Science, and Transportation.",
    policyArea: "Science, Technology, Communications",
    url: "https://www.congress.gov/bill/119th-congress/senate-bill/278",
  },
  representative: {
    name: "Michael McCaul",
    title: "Representative",
    district: "Texas 10th District",
  },
  sources: [
    {
      id: "bill-text",
      label: "S. 278 — Introduced Text",
      url: "https://www.congress.gov/119/bills/s278/BILLS-119s278is.pdf",
      publisher: "Congress.gov",
      excerpt: "The bill would prohibit users under 13 from accessing social media platforms and personalized recommendation systems for individuals under 17.",
    },
    {
      id: "bill-status",
      label: "S. 278 — Actions and Status",
      url: "https://www.congress.gov/bill/119th-congress/senate-bill/278/all-actions",
      publisher: "Congress.gov",
      excerpt: "The proposal was introduced on January 28, 2025 and referred to the Senate Commerce Committee.",
    },
    {
      id: "committee-report",
      label: "Senate Commerce Committee Report 119-33",
      url: "https://www.congress.gov/119/crpt/srpt33/CRPT-119srpt33.pdf",
      publisher: "Congress.gov",
      excerpt: "The committee report describes restrictions on personalized recommendation systems and social-media access for children and teens.",
    },
  ],
  evidence: [
    {
      id: "age-limit",
      heading: "A national minimum age",
      explanation: "The introduced bill would bar children under 13 from maintaining social-media accounts. Platforms would need a way to apply that rule.",
      sourceIds: ["bill-text"],
      perspective: "fact",
    },
    {
      id: "recommendations",
      heading: "Recommendation feeds would change",
      explanation: "For users under 17, platforms could not use personal data to power personalized recommendation systems, with limited exceptions described in the bill.",
      sourceIds: ["bill-text", "committee-report"],
      perspective: "fact",
    },
    {
      id: "safety-case",
      heading: "The safety argument",
      explanation: "A supporter could argue that reducing data-driven recommendations limits systems designed to keep young users scrolling and gives families a clearer baseline protection.",
      sourceIds: ["bill-text", "committee-report"],
      perspective: "supporting",
    },
    {
      id: "choice-case",
      heading: "The choice and enforcement argument",
      explanation: "An opponent could ask whether a federal age rule overrides family choice and whether age checks can work without collecting additional identifying information.",
      sourceIds: ["bill-text"],
      perspective: "opposing",
    },
    {
      id: "not-law",
      heading: "This is not law",
      explanation: "S. 278 was referred to committee. It would still need congressional approval and the president’s signature before its rules could take effect.",
      sourceIds: ["bill-status"],
      perspective: "fact",
    },
  ],
  questions: [
    {
      id: "q-age",
      prompt: "Under the introduced bill, which group could not maintain a social-media account?",
      choices: ["Everyone under 18", "Children under 13", "Only students during school", "Anyone without a government ID"],
      correctChoice: 1,
      explanation: "The introduced text sets the account restriction at under 13; its recommendation-system rule applies to a different age range.",
      sourceIds: ["bill-text"],
    },
    {
      id: "q-status",
      prompt: "What does the bill’s current status tell us?",
      choices: ["It is already federal law", "It passed both chambers", "It was referred to a Senate committee", "The Supreme Court approved it"],
      correctChoice: 2,
      explanation: "The actions record shows referral to committee, an early stage in the legislative process.",
      sourceIds: ["bill-status"],
    },
    {
      id: "q-source",
      prompt: "Which statement is an argument rather than a fact stated by the bill?",
      choices: ["The bill is numbered S. 278", "The bill was referred to committee", "The bill would make young people safer online", "The bill addresses recommendation systems"],
      correctChoice: 2,
      explanation: "Safety is a predicted outcome and therefore an argument to evaluate. The other choices describe the official record or bill text.",
      sourceIds: ["bill-text", "bill-status"],
    },
  ],
  publishedAt: "2026-09-13T12:00:00.000Z",
};

const now = "2026-09-13T12:00:00.000Z";
export const DEMO_RESPONSES: MissionResponse[] = [
  {
    participantId: "27e9817a-723f-4e02-9bf1-7df746fc86d3",
    missionId: DEMO_MISSION.id,
    nickname: "Bluebonnet",
    currentChapter: 6,
    initialPosition: "support",
    initialConfidence: 2,
    evidenceRatings: { "age-limit": 1, recommendations: 2, "safety-case": 2, "choice-case": -1, "not-law": 1 },
    answers: { "q-age": 1, "q-status": 2, "q-source": 2 },
    reflection: "Platforms should not be able to optimize a feed for a teenager without meaningful limits.",
    personalConnection: "I have opened an app for one message and realized much later that I was still scrolling.",
    finalPosition: "support",
    finalConfidence: 4,
    letter: "Dear Representative McCaul,\n\nI am a student in your district writing about S. 278, the Kids Off Social Media Act. I support limits on personalized recommendation systems for teens because I have opened an app for one message and realized much later that I was still scrolling. I also think any age-checking system should protect privacy and avoid collecting more personal information.\n\nPlease consider both youth safety and privacy as Congress debates this proposal.\n\nRespectfully,\nA student constituent",
    reviewStatus: "submitted",
    completedAt: now,
    updatedAt: now,
  },
  {
    participantId: "d523455b-0462-48b4-85ac-57c29baf9b62",
    missionId: DEMO_MISSION.id,
    nickname: "Cedar",
    currentChapter: 6,
    initialPosition: "unsure",
    initialConfidence: 1,
    evidenceRatings: { "age-limit": 0, recommendations: 1, "safety-case": 1, "choice-case": 2, "not-law": 1 },
    answers: { "q-age": 1, "q-status": 2, "q-source": 2 },
    reflection: "I want stronger safety rules, but I am not convinced platforms can verify age without creating a different privacy problem.",
    personalConnection: "My friends and I use group accounts and shared devices, so age checks may not be simple.",
    finalPosition: "unsure",
    finalConfidence: 3,
    letter: "Dear Representative McCaul,\n\nI am a student constituent learning about S. 278. I agree that young people deserve protection from recommendation systems designed around personal data. However, I am concerned that enforcing age rules could require platforms to collect additional identifying information.\n\nPlease ask how the proposal will protect privacy while enforcing its age requirements.\n\nRespectfully,\nA student constituent",
    reviewStatus: "approved",
    completedAt: now,
    updatedAt: now,
  },
];
